### PR TITLE
Move output handler

### PR DESCRIPTION
**Pull request by joncrobe**
output handler has been moved from simulation to UI. Also took a look at the issue xavier was having with grass not moving, but grass shouldn't be moving.

### CODE REVIEW

**Comment by Xavbeat03** [comment]
Exception in thread "Thread-0" java.lang.ClassCastException: class team.rocket.Entities.Grass cannot be cast to class team.rocket.Entities.AbstractAnimal (team.rocket.Entities.Grass and team.rocket.Entities.AbstractAnimal are in unnamed module of loader 'app')
        at team.rocket.Simulation.moveAnimal(Simulation.java:195)
        at team.rocket.Simulation.run(Simulation.java:106)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Xavbeat03** [comment]
This error occurs when running the program with grass

**Review by Xavbeat03 — CHANGES_REQUESTED** [review]
Please fix the error attached in the conversation.

**Comment by Xavbeat03** [comment]
It tries to make grass move when it shouldn't. All you should need to do is check the type of the organism in the moveAnimal method and check that it's typeof AbstractOrganism.

**Comment by joncrobe** [comment]
issue with grass has been fixed

**Review by Xavbeat03 — APPROVED** [review]
lgtme

**Pull request merged**
